---
abstract: 'Yet another scraping library like jQuery'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Query
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Web::Query:
    file: lib/Web/Query.pm
    version: 0.18
requires:
  HTML::Entities: 0
  HTML::Selector::XPath: 0.06
  HTML::TreeBuilder::XPath: 0.12
  LWP::UserAgent: 6
  Scalar::Util: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Web-Query/issues
  homepage: https://github.com/tokuhirom/Web-Query
  repository: git://github.com/tokuhirom/Web-Query.git
version: 0.18
x_contributors:
  - 'Hiroki Honda <cside.story@gmail.com>'
  - 'Oleg <verdrehung@gmail.com>'
  - 'Kang-min Liu <gugod@gugod.org>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'Carlos Fernando Avila Gratz <cafe01@gmail.com>'
  - 'Carlos Fernando Avila Gratz <cafe@q1software.com>'
