---
abstract: 'Yet another scraping library like jQuery'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Query
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Web::Query:
    file: lib/Web/Query.pm
    version: 0.11
requires:
  HTML::Selector::XPath: 0.06
  HTML::TreeBuilder::XPath: 0.12
  LWP::UserAgent: 6
  Scalar::Util: 0
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
